Update README.md
ukui/ukui-desktop-environment pull request #42
Opened 2022-04-02 03:54 UTC by hemantsarthak

Removed $ from commands for easier, error free copy pasting to console/terminal.

2023-07-11 18:45 UTC, rokejulianlockhart commented
Think you could fix

> Error Fetching Resource

from https://camo.githubusercontent.com/6cfc399dd7f814b83f4eb89b5d145f7b3657bf1f52ba292a8f0b96723b854466/68747470733a2f2f7777772e756b75692e6f72672f696d616765732f666561747572655f6c69312e706e67 too?

2023-07-11 18:46 UTC, rokejulianlockhart requested changes

2023-07-11 18:46 UTC, rokejulianlockhart commented on README.md
Think you could fix

> Error Fetching Resource

from https://camo.githubusercontent.com/6cfc399dd7f814b83f4eb89b5d145f7b3657bf1f52ba292a8f0b96723b854466/68747470733a2f2f7777772e756b75692e6f72672f696d616765732f666561747572655f6c69312e706e67 too?

2026-05-21 08:21 UTC, closed without merging

2026-05-21 08:21 UTC, handsome-feng commented
We moved to gitee.com/openkylin/ukui-desktop-environment. Thanks!

2026-05-21 11:17 UTC, beedell-roke commented
@handsome-feng, I have created [`gitee.com/openkylin/ukui-desktop-environment/pulls/16`](https://gitee.com/openkylin/ukui-desktop-environment/pulls/16), but because I am not Chinese, I cannot sign the CLA.

Additionally, you may want to note [`plaintextoffenders/plaintextoffenders/issues/40`](https://github.com/plaintextoffenders/plaintextoffenders/issues/40#issue-4494138074), if you don't already enforce 2FA.